teams:
  - name: karthik
    iam_user: karthik
    email: karthikkunchala170@gmail.com

  - name: python
    iam_user: python_script_runner
    email: karthikkunchala170@gmail.com

  - name: platform
    iam_user: terraform-execution
    email: karthikkunchala170@gmail.com

rotation:
  threshold_days: 15
  observation_days: 2

notification:
  sns_topic_arn: arn:aws:sns:ap-south-1:897722700244:iam-key-rotation